# Generated by Django 5.2.8 on 2025-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
